runs:
  using: "composite"
  steps:
    - name: --- Install pip deps ---
      working-directory: python-deploy
      run: echo Installing pip dependencies is starting ...
      shell: cmd
      
    - name: Install dependencies
      working-directory: python-deploy
      run: pip install -r requirements.txt
      shell: cmd