inputs:
  port:
    description: 'Port for node application to run'
    default: 1010
  enviroment:
    description: 'Enviroment for node application'
    default: 'DEV'
runs:
  using: "composite"
  steps:
    - name: Print output
      working-directory: python-deploy
      run: echo Deployment to ${{ inputs.enviroment }} has started ...
      shell: cmd

    - name: Install pm2
      working-directory: python-deploy
      run: npm install -g pm2
      shell: cmd

    - name: Delete services
      working-directory: python-deploy
      run: pm2 delete greetings-${{ inputs.enviroment }} & set "errorlevel=0"
      shell: cmd

    - name: Start services
      working-directory: python-deploy
      run: pm2 start app.py --name greetings-${{ inputs.enviroment }} -- --port ${{ inputs.port }}
      shell: cmd