# This is a basic workflow to help you get started with Actions

name: python-greetings

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:


jobs:

  install-pip-deps:
    name: install-pip-deps
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'AKrasts/python-greetings'
          path: 'python-test'
      - uses: ./.github/actions/install-pip-deps


  deploy-dev:
    name: Deploy DEV
    runs-on: self-hosted
    needs: [install-pip-deps]
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'AKrasts/python-greetings'
          path: 'python-test'
      - uses: ./.github/actions/deploy
        with:
          port: 7001
          enviroment: 'DEV'

  tests-dev:
    name: Tests DEV
    runs-on: self-hosted
    needs: [deploy-dev]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'AKrasts/python-greetings'
          path: 'python-test'
      - uses: ./.github/actions/test
        with:
          enviroment: 'DEV'
  
  deploy-stg:
    name: Deploy STG
    runs-on: self-hosted
    needs: [tests-dev]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'AKrasts/python-greetings'
          path: 'python-test'
      - uses: ./.github/actions/deploy
        with:
          port: 7002
          enviroment: 'STG'

  tests-stg:
    name: Tests STG
    runs-on: self-hosted
    needs: [deploy-stg]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'AKrasts/python-greetings'
          path: 'python-test'
      - uses: ./.github/actions/test
        with:
          enviroment: 'STG'

  deploy-preprd:
    name: Deploy PREPRD
    runs-on: self-hosted
    needs: [tests-stg]
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'AKrasts/python-greetings'
          path: 'python-test'
      - uses: ./.github/actions/deploy
        with:
          port: 7003
          enviroment: 'PREPRD'

  tests-preprd:
    name: Tests PREPRD
    runs-on: self-hosted
    needs: [deploy-preprd]
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'AKrasts/python-greetings'
          path: 'python-test'
      - uses: ./.github/actions/test
        with:
          enviroment: 'PREPRD'
        
                

  deploy-prd:
    name: Deploy PRD
    runs-on: self-hosted
    needs: [tests-preprd]
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'AKrasts/python-greetings'
          path: 'python-test'
      - uses: ./.github/actions/deploy
        with:
          port: 7004
          enviroment: 'PRD'

  tests-prd:
    name: Tests PRD
    runs-on: self-hosted
    needs: [deploy-prd]
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'AKrasts/python-greetings'
          path: 'python-test'
      - uses: ./.github/actions/test
        with:
          enviroment: 'PRD'

